version: "3.7"

services:
  php:
    build:
      context: .
    volumes:
      - ./my-flamework:/work
    networks:
      - container-link
  nginx:
    image: nginx:1.20-alpine
    depends_on:
      - php
    volumes:
      - ./my-flamework:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - container-link
    environment:
      - VIRTUAL_HOST=api.localhost # nginx-proxyのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - LETSENCRYPT_HOST=api.localhost # Let's Encryptのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - LETSENCRYPT_EMAIL=xxxx@gmail.com # Let's Encryptのメール設定
      - LETSENCRYPT_TEST=true # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
      - CERT_NAME=default # ローカルで認証局を立てるときに使う ※本番ではLet's Encryptから直接取得するのでコメントアウトする
      - HTTPS_METHOD=noredirect # リダイレクトを無効にする
    working_dir: /work
    restart: always
    ports: 
      - 10080:80

networks:
  container-link:
    name: container_network
    external: true
